apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-api
  template:
    metadata:
      labels:
        app: k3s-api
    spec:
      containers:
      - name: k3s-api
        image: k3s-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
