apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k3s-api
    spec:
      containers:
        - name: k3s-api
          image: k3s-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:                         # ← bu yerga ko‘chiriladi
            requests:
              cpu: 100m
            limits:
              cpu: 200m
